
<?php Tag::css('galeria')?>



<section class="left">
	<hr>


	<article class="album">
		<section class="fondo1">
		<section class="fondo2">
				<section class="imagen">
<?php echo Html::img('slide/img_app.png', 'esto es una foto')?>
				</section>
		</section>
		</section>
				<section class="texto">
					<h3> Aniversario de falconia , donde celebraron los trabajadores , y nunca falto un payaso que se rasco <span> -- 31/02/2014-- </span>
					</h3>

				</section>

				<hr/>

	</article>



		<article class="album">
		<section class="fondo1">
		<section class="fondo2">
				<section class="imagen">
<?php echo Html::img('slide/img_media.jpg', 'esto es una foto')?>
				</section>
		</section>
		</section>
				<section class="texto">
					<h3> Aniversario de falconia , donde celebraron los trabajadores , y nunca falto un payaso que se rasco <span> -- 31/02/2014-- </span>
					</h3>

				</section>

				<hr/>

	</article>


		<article class="album">
		<section class="fondo1">
		<section class="fondo2">
				<section class="imagen">
<?php echo Html::img('logo.png', 'esto es una foto')?>
				</section>
		</section>
		</section>
				<section class="texto">
					<h3> Aniversario de falconia , donde celebraron los trabajadores , y nunca falto un payaso que se rasco <span> -- 31/02/2014-- </span>
					</h3>

				</section>

				<hr/>

	</article>

		<article class="album">
		<section class="fondo1">
		<section class="fondo2">
				<section class="imagen">
<?php echo Html::img('logo_f.png', 'esto es una foto')?>
				</section>
		</section>
		</section>
				<section class="texto">
					<h3> Aniversario de falconia , donde celebraron los trabajadores , y nunca falto un payaso que se rasco <span> -- 31/02/2014-- </span>
					</h3>

				</section>

				<hr/>

	</article>





</section>



<section class="right">


</section>



