
<?php Tag::css('galeria')?>



<section class="left">
	<hr>
	<article class="album">
				<h3>Titulo un Poco más Largo</h3>
		<p>Fecha:31/02/2014</p>
		<?php echo Html::img('logo_negro.png', 'esto es una foto')?>

	</article>
	<article class="album">

		<hr/>
		<?php echo Html::img('slide/noticiero_que_pasa_11.jpg', 'esto es una foto')?>
		<section class="texto">
				<h3> <span>31/02/2014 - </span> las mujeres haciendo un harlem shake</h3>
		
		</section>

	</article>
	<article class="album">
		<section class="imagen">
			<hr/>
		<?php echo Html::img('slide/img_app.png', 'esto es una foto')?>
		</section>
		<section class="texto">
				<h3> Aniversario de falconia , donde celebraron los trabajadores , y nunca falto un payaso que se rasco <span> -- 31/02/2014-- </span> </h3>
				
		</section>
		
		<hr>

	</article>





</section>



<section class="right">


</section>



