
<?php Tag::css('galeria')?>
<section class="left">
	<hr>
	<article class="album">
				<h3>Titulo un Poco más Largo</h3>
		<p>Fecha:31/02/2014</p>
		<?php echo Html::img('logo_negro.png', 'esto es una foto')?>

	</article>
	<article class="album">
		<?php echo Html::img('slide/noticiero_que_pasa_11.jpg', 'esto es una foto')?>
				<h3>las mujeres haciendo un harlem shake</h3>
		<p>Fecha:31/02/2014</p>
		

	</article>
	<article class="album">
		<section class="imagen">
		<?php echo Html::img('slide/img_app.png', 'esto es una foto')?>
		</section>
		<section class="texto">
				<h3>Aninversario de falconia , donde celebraron los trabajadores , y nunca falto un payaso que se rasco</h3>
				<p>Fecha:31/02/2014</p>
		</section>
		


	</article>





</section>



<section class="right">


</section>



