<div class="contenido">
    <a id="descripcion"></a>
    <!-- Mensaje -->
    <div class="contenedor-mensaje">
        <div class="mensaje">                        
            <?php View::content(); echo "\r\n"; ?>
        </div>
    </div>
    <h2 class="contenido-titulo">La empresa</h2>
    <div class="left">
        <p>El canal FALCONIA fue fundado el 4 de Abril del año 1999 por un grupo de accionistas de nacionalidad argentina, quienes además instalaron en Paraguaná la red de cable llamada Intercable.
FALCONIA surgió como estrategia de venta de la televisión por cable en una región donde predominaba la señal por antena parabólica.
Fueron sus fundadores: Gonzalo Cianciarullo, Jorge Puente y Pedro Conde, siendo su creador el primero de estos.
</p><p>
La primera transmisión del Canal Falconía se logró el 04/04/99, fecha que signa el inicio de la historia del canal. La grilla de programación registra que a las 08:00 p.m. la primera transmisión fue del Noticiero ¿Qué Pasa?.
El equipo de transmisión y edición con el cual se inició Falconía contó con una Cámara, un Sistema de Edición TRINITY, dos Máquinas Editoras Formato DVC PRO Panasonic y una SUPER VHS con sus respectivos monitores, una Matriz Botonera y una Consola de Audio.
Dada las limitadas condiciones técnicas y de recurso humano que caracterizaron el inicio de este canal, la programación diaria tenía una duración de cuatro horas.
Inmediatamente comenzaron a incorporarse nuevos programas: Impacto Deportivo que se transmitía a las 9:00 p.m. los días Martes, La Santa Misa los Domingos a las 6:00 p.m., grabación del Piloto y transmisión del Programa de Marlene, ubicado en el horario de 09:00 p.m. los días Viernes, y Vídeos Musicales.
</p><p>
Con el correr del tiempo se fueron creando programas tales como: Venezuela en Especial, El Mundo de Yaneth Muñoz , Cita con Marlene, Zona Libre , Comentario, Emisión Meridiana del Noticiero, Resumen Semanal, Falcón es Así, ¿Que Pasa Contigo?, Así de Genial, Como Todo, Nada Más y Nada Menos, Medalla de Oro, y Desayuno de Noticias
Un cambio fundamental en la historia de FALCONIA se registra el 28 de Noviembre de 2001, cuando empresarios de la zona adquirieron el Canal en su totalidad.
</p><p>
El crecimiento paulatino del Canal y la inclusión de nuevo personal (aumento del recurso humano), permitió extender la programación de 07:00 de la mañana a 12:00 de la noche
Al incorporarse capital falconiano se establecieron nuevas metas de trabajo y de inversión, la línea que prevalece es la informativa; y es así como se adquirió nuevo equipo de transmisión y de edición, se creó la corresponsalía FALCONIA en la ciudad de Coro, la cual inició sus operaciones el 24 de enero de 2002. Esta corresponsalía convierte a FALCONIA en el primer Canal que verdaderamente se precia de Regional, pues fusiona en una misma pantalla las realidades de los centros urbanos más importantes de la región. También se incorporaron nuevos programas, y uno de los logros más importantes se cristalizó con el acuerdo de transmisión compartida con el Canal de Televisión CMT, con ello se extiende la transmisión a 24 Horas.
</p><p>
Otro paso importante para FALCONIA, es haberse convertido en el primer Medio de Comunicación de la región en realizar una Pre-Venta Televisiva, la misma se realizó el 03 de Octubre de 2002, siendo esta fecha propicia para dar un adelanto de la nueva imagen digitalizada de FALCONIA, la cual tuvo su fecha de lanzamiento el 01 de Noviembre de 2002. Desde ese entonces el canal ha ido creciendo tanto en número de personal como en programación propia, permitiéndonos concentrar en nuestra pantalla 19 horas de producción local..</p>
        <a id="mision"></a>
        <h3 class="contenido-subtitulo"> Nuestra Misión</h3>
        <div class="texto">
            <p>Falconía se perfila como el único medio de comunicación local que precisa un formato televisivo de calidad, ajustado a los requerimientos y exigencias tecnológicas del momento, por cuanto el esfuerzo estratégico va dirigido al logro de objetivos puntuales que rigen nuestra filosofía de trabajo, consolidando un recurso humano proactivo e incrementando nuestra programación, manteniendo el estatus que hemos alcanzado, aspirando máxima rentabilidad, equipos de punta y capacitación constante para nuestro personal, posicionándonos como único medio capaz de cubrir todas las necesidades del colectivo. Porque definitivamente en Falconía somos televisión….</p>
        </div>
        <a id="vision"></a>
        <h3 class="contenido-subtitulo">Nuestra Visión</h3>
        <div class="texto">
            <p>El canal 6 de Intercable, Falconía, como medio de comunicación local tiene la misión de informar, educar y entretener al televidente, y ser un ente multiplicador en la difusión noticiosa de nuestro Estado, dando a conocer los problemas, necesidades, bondades o debilidades de nuestras comunidades e instituciones que hacen vida en la región y captar de esta manera la atención de todos los sectores de interés que puedan dar soluciones efectivas a las problemáticas existentes. Por otro lado Falconía trabaja día a día por consolidar alianzas comerciales que se traduzcan en mayor productividad y beneficios para nuestros patrocinantes y por ende para la empresa..</p>
        </div>
        <a id="direccion"></a>
        <h3 class="contenido-subtitulo">Dirección</h3>
        <div class="texto">
            <p>Calle Urdaneta en Colón y Altagracia, Sector Caja de Agua, Punto Fijo, Edo. Falcón, Telefax 0269 - 2469970 - 2479255.</p>
        </div>
    </div>
    <div class="right">
        <h3 style="text-align: center;" class="contenido-subtitulo">Know - how</h3>
        <div class="texto">
            <h3 class="contenido-subtitulo">Planeación</h3>
            <?php echo Html::img('pagina/kh_planeacion.png', 'planeacion', array('border'=>'0', 'width'=>'82', 'heigth'=>'82', 'class'=>'floated')); ?>
            <p><strong>Es la primera etapa de cada proyecto. </strong><br />
            Escuchamos a nuestros clientes de manera especial; determinamos los alcances, 
            objetivos, arquitectura e infraestrucura técnica.
            <?php echo Html::link('know-how/#planeacion','Mas »');?><br />
            </p>

            <h3 class="contenido-subtitulo">Producción</h3>
            <?php echo Html::img('pagina/kh_produccion.gif', 'producción', array('border'=>'0', 'width'=>'82', 'heigth'=>'82', 'class'=>'floated')); ?>
            <p><strong>Aquí marcamos la diferencia. </strong><br />
            Este es el proceso en donde  más interactuamos con el cliente mostrando los
            avances y prototipos de cada proyecto.  Nuestro equipo se encarga del análisis de las pruebas
            y se utiliza como verificación del correcto funcionamiento del mismo.
            <?php echo Html::link('know-how/#produccion','Mas »');?><br />
            </p>
            
            <h3 class="contenido-subtitulo">Feedback</h3>
            <?php echo Html::img('pagina/kh_analisis.png', 'feedback', array('border'=>'0', 'width'=>'82', 'heigth'=>'82', 'class'=>'floated')); ?>
            <p><strong>Porque no es solamente producir.</strong><br />
            Una vez nuestro trabajo es entregado analizamos los indicadores de usabilidad, 
            estabilidad, crecimiento y tráfico* para mejorar cada vez mas calidad de nuestros productos.
            <?php echo Html::link('know-how/#feedbak','Mas »');?><br /></p>
        </div>
        <div class="bg"></div>
    </div>    
    <div class="clr"></div>
</div>
  