<?php Tag::css('slider') ?>
<?php echo Tag::js('jquery/easySlider'); ?>
<script type="text/javascript">
    $(document).ready(function(){
        $("#slider").easySlider({ prevText: '', nextText: '', controlsBefore: '<p id="controls">', controlsAfter: '</p>', controlsShow: true, auto: true, pause: 5000, continuous: true });
    });
</script>


<!-- Slider -->
<section class="contenedor">
    <div class="slider">
        <div id="slider">
            <ul>
                <li class="slide">
                    <p class="slide_img"><?php echo Html::img('slide/noticiero_que_pasa_11.jpg', 'Diseño web', array('width'=>'450', 'height'=>'225', 'border'=>'0')); ?></p>
                    <div class="slide_text">
                        <h2>Que Pasa? <br /><span>El espacio informativo de FALCONÍA</span></h2>
                        <p> enterate de lo que pasa en Falcón, el noticiero qué pasa en sus en dos emisiones, meridiana a la 1 p.m. rep 17:00 y estelar a las 8 p.m. rep 23:00 - 08:30 a.m.  </p>
                        <div class="horario">
                           <p>Lun a Ver de 5:00pm a 21:00pm.  </p>
                        </div>
                    </div>
                </li>
                <li class="slide">
                    <p class="slide_img"><?php echo Html::img('slide/img_app.png', 'Aplicaciones web', array('width'=>'450', 'height'=>'225', 'border'=>'0')); ?></p>
                    <div class="slide_text">
                        <h2>Aplicaciones Web <br /><span>Aumente su productividad!</span></h2>
                        <p class="list">Portales web.</p>
                        <p class="list">Sistemas de información.</p>
                        <p class="list">Desarrollo de software a su medida.</p>
                        <div class="horario">
                             <p> Lun a Ver de 5:00pm a 21:00pm. </p>
                        </div>
                    </div>
                </li>

            </ul>
        </div>
    </div>
    <div class="slider_shadow"></div>
    <div id="resumen-galeria">

        <span>La pasión por nuestro trabajo se ve reflejada en cada proyecto.</span>
        <div class="clr"></div>
    </div>
    <div class="clr"></div>
</section>

<!-- Contenido -->
<section class="contenedor">
    <section class="contenido">
        <section class="left">
            <article>
                <header>
            <h3 class="contenido-subtitulo">Welcome to Our Website</h3>
        </header>
            <p>Morbi pharetra mollis tempus. Donec leo urna, sodales vel imperdiet ut, adipiscing ac mi. Praesent laoreet imperdiet orci in posuere. Quisque ipsum lorem, interdum et adipiscing vitae, venenatis ac lectus. Vivamus sed dui porttitor quam venenatis posuere.<br />

              Morbi pharetra mollis tempus. Donec leo urna, sodales vel imperdiet ut, adipiscing. Praesent laoreet imperdiet orci in posuere.<a href="#"> Ver Más »</a></p>

            </article>
            <article>
                <header>
            <h3 class="contenido-subtitulo">Welcome to Our Website</h3>
        </header>
            <p>Morbi pharetra mollis tempus. Donec leo urna, sodales vel imperdiet ut, adipiscing ac mi. Praesent laoreet imperdiet orci in posuere. Quisque ipsum lorem, interdum et adipiscing vitae, venenatis ac lectus. Vivamus sed dui porttitor quam venenatis posuere.<br />

              Morbi pharetra mollis tempus. Donec leo urna, sodales vel imperdiet ut, adipiscing. Praesent laoreet imperdiet orci in posuere.<a href="#"> Ver Más »</a></p>

            </article>
        </section>
        <section class="right">
            <article>
                <header>
                    <h3 class="contenido-subtitulo">What Do We Do</h3>
                </header>
                    <?php echo Html::img('pagina/img_1.gif', 'picture', array('class'=>'floated',' border'=>'0')); ?>
                <p><strong>Fusce vehicula dignissim ligula</strong>. <br />
                  Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. <a href="#">Ver Más »</a>
                </p>
            </article>
            <div class="bg"></div>
            <article>
                <header>
                    <h3 class="contenido-subtitulo">What Do We Do</h3>
                </header>
                    <?php echo Html::img('pagina/img_1.gif', 'picture', array('class'=>'floated',' border'=>'0')); ?>
                <p><strong>Fusce vehicula dignissim ligula</strong>. <br />
                  Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. <a href="#">Ver Más »</a>
                </p>
            </article>
<!-- Banner Vertical Comercial -->
 <div class="bg"></div>
            <div class="b_vertical">adwords </div>
        </section>
        </section>
        <div class="clr"></div>
    </section>
    <div class="clr"></div>
</section>