<!DOCTYPE html>
    <head>
    <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
    <meta name="copyright" content="Dailyscript &copy; <?php echo date("Y");?>" />
    <meta name="keywords" content="Dailyscript" />
    <meta name="robots" content="noindex,nofollow" />
    <meta name="languaje" content="es-CO" />
    <meta name="geo.placename" content="Colombia" />
    <title><?php echo $title ?></title>
    <?php Tag::css('default') ?>
    <?php Tag::css('style') ?>
    <?php echo Html::includeCss() ?>
    <?php echo Tag::js('jquery/jquery.min'); ?>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#logo,#navegador").hide().fadeIn(1500);
        });
    </script>
    </head>
    <body>

        <!-- Cabecera -->
        <?php View::partial('dailyscript/cabecera');?>

        <!-- Navegador -->
        <?php View::partial('dailyscript/navegador', false, array($controller_name=>$controller_name) );?>

        <!-- Cuerpo -->
        <div id="pagina">
            <!-- Contenedor principal -->
            <div class="contenedor">
                <!-- Contenido -->
                <?php View::content(); ?>
              <div class="clr"></div>
            </div>
        </div>

        <!-- Extra -->
        <?php View::partial('dailyscript/extra');?>

        <!-- Pie -->
        <?php View::partial('dailyscript/pie');?>

    </body>
</html>
