<!DOCTYPE html>
<html>
    <head>
    <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
    <meta name="copyright" content="Falconia &copy; 2013" />
    <meta name="keywords" content="Falconia" />
    <meta name="robots" content="index,follow" />
    <meta name="languaje" content="es-CO" />
    <meta name="geo.placename" content="Colombia" />
    <?php echo Html::includeHeadLinks(); ?>
    <title><?php echo $title ?></title>
    <?php Tag::css('default') ?>
    <?php Tag::css('style') ?>
    <?php echo Html::includeCss() ?>
    <?php echo Tag::js('jquery/jquery.min'); ?>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#logo,#navegador").hide().fadeIn(1500);
        });
    </script>
    </head>
    <body>

        <!-- Cabecera -->
        <?php View::partial('dailyscript/cabecera');?>

        <!-- Navegador -->
        <?php View::partial('dailyscript/navegador', false, array($controller_name=>$controller_name) );?>

        <!-- Cuerpo -->
        <div id="pagina">
        <?php View::content(); ?>
        </div>

        <!-- Extra -->
        <?php View::partial('dailyscript/extra');?>

        <!-- Pie -->
        <?php View::partial('dailyscript/pie');?>

    </body>
</html>
