<?php tag::css('envivo');?>


<section class="contenido">

	<h1> Señal en Vivo</h1>
		<div class="streaming"> <span>contenedor del streaming de video</span></div>

</section>

<section class="contenido">

		<section class="left">

		 <article>
                <header>
                    <h3 class="contenido-subtitulo">What Do We Do</h3>
                </header>
                    <?php echo Html::img('pagina/img_1.gif', 'picture', array('class'=>'floated',' border'=>'0')); ?>
                <p><strong>Fusce vehicula dignissim ligula</strong>. <br />
                  Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. <a href="#">Ver Más »</a>
                </p>
            </article>
		</section>



		<section class="right">

		<div class="b_vertical">adwords </div>
		</section>
</section>
